// Produces the two browser vendor files. Run once per dependency bump and commit the output:
//   public/vendor/yjs.js     - yjs bundled as a single minified ESM module
//   public/vendor/qrcode.js  - qrcode-generator (its ESM build), copied verbatim with a banner
import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
mkdirSync('public/vendor', { recursive: true });

const yjsVersion = require('yjs/package.json').version;
await build({
  entryPoints: ['scripts/yjs-entry.mjs'],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: ['es2020'],
  minify: true,
  legalComments: 'none',
  outfile: 'public/vendor/yjs.js',
  banner: { js: `/* yjs ${yjsVersion} - generated by scripts/vendor.mjs, do not edit */` },
});

// qrcode-generator's package.json is not exported, so locate it from the resolved main file.
const qrMain = require.resolve('qrcode-generator');           // .../qrcode-generator/dist/qrcode.js
const qrRoot = dirname(dirname(qrMain));
const qrPkg = JSON.parse(readFileSync(join(qrRoot, 'package.json'), 'utf8'));
const qr = readFileSync(join(qrRoot, 'dist', 'qrcode.mjs'), 'utf8');
writeFileSync('public/vendor/qrcode.js', `/* qrcode-generator ${qrPkg.version} - generated by scripts/vendor.mjs, do not edit */\n${qr}`);

console.log(`vendored yjs ${yjsVersion} and qrcode-generator ${qrPkg.version}`);
